
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexis Moreno
 */
public class Principal extends javax.swing.JFrame {
    DefaultTableModel p = new DefaultTableModel();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        p.addColumn("IDPRODUCTOS");
        p.addColumn("DESCRIPCION");
        p.addColumn("PRECIO");
        p.addColumn("EXISTENCIA");
        this.setLocationRelativeTo(null);
        tblP.setModel(p);
        consulta("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblP = new javax.swing.JTable();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        cmbBuscar = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jcbMostrar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Insertar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btneliminar.setText("Eliminar");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        btnActualizar.setText("Actualizar");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        tblP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Domicilio", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tblP);

        lblClave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClave.setText("Clave");

        lblBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBuscar.setText("Buscar en");

        cmbBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NOMBRE", "DIRECCION", "TELEFONO" }));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jcbMostrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcbMostrar.setSelected(true);
        jcbMostrar.setText("Mostrar todos");
        jcbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscar)
                            .addComponent(lblClave))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jcbMostrar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClave)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMostrar))))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String where = "";
        
        jcbMostrar.setSelected(false);
        switch(cmbBuscar.getSelectedIndex()){
            case 0:
                where = "WHERE ID = "+txtClave.getText();
                break;
            default:
                where = "WHERE "+cmbBuscar.getSelectedItem().toString().toUpperCase()+
                        " LIKE '%"+txtClave.getText()+"%'";
        }
        consulta(where);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jcbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMostrarActionPerformed
        jcbMostrar.setSelected(true);
        consulta("");
        
    }//GEN-LAST:event_jcbMostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Insertar insertar = new Insertar(this, true);
        insertar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if(tblP.getSelectedRow()<0){
            mensaje("ERORR\n DEBES SELECCIONAR EL RENGLON DE LA TABLA PARA PODER ELIMINAR");
        return;
        }
        String id = p.getValueAt(tblP.getSelectedRow(), 0).toString();
        int resp = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas eliminar IDPRODUCTOS"+id);
        if(resp == JOptionPane.OK_OPTION){
            eliminar(id);
        }
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(tblP.getSelectedRow()<0){
            mensaje("ERORR\n DEBES SELECCIONAR EL RENGLON DE LA TABLA PARA PODER ACTUALIZAR");
        return;
        }
        String id = p.getValueAt(tblP.getSelectedRow(), 0).toString();
        Actualizar act = new Actualizar(this,true,id);
        act.setVisible(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void consulta(String where){
        try{
           DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/Productos","root","");
           Statement s = conexion.createStatement();
           String SQL = "SELECT * FROM `Productos`.`Producto`";
           
           if(where.isEmpty()){
               //Entra si el where NO esta vacio
        SQL += where;
    }           
           ResultSet resultadoConsulta = s.executeQuery(SQL);
           
           //Este if es para ¿Existen rengoles de consulta anterior?
           if(p.getRowCount()>0){
               //Si hay renglones, el sig. ciclo los BORRA
               int total = p.getRowCount();
               for (int i = 1; i <= total; i++) {
                   p.removeRow(0);
               }
           }
           
           while(resultadoConsulta.next()){
               String[] data = new String[4];
               data[0] = ""+resultadoConsulta.getInt(1);
               data[1] = ""+resultadoConsulta.getString(2);
               data[2] = ""+resultadoConsulta.getFloat(3);
               data[3] = ""+resultadoConsulta.getInt(4);
               p.addRow(data);
           }
           conexion.close();
        }catch(Exception e){mensaje(e.getMessage());}
    }
    private void eliminar(String id){
        try{
           DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/Productos","root","");
           Statement s = conexion.createStatement();
           String SQL = "DELETE FROM `Producto` WHERE IDPRODUCTOS = "+id;
           
           int resultado = s.executeUpdate(SQL);
           
           if(resultado == 0){
               mensaje("ERROR:\nNo se pudo eliminar IDPRODUCTOS"+id);
           }else{
               mensaje("¡SE BORRO CON EXITO!");
           }
             conexion.close();
    }   catch (SQLException e) {
            mensaje(e.getMessage());
    }    
        consulta("");
    }//eliminar//eliminar
    
    private void mensaje(String m){
        JOptionPane.showMessageDialog(this,m);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JCheckBox jcbMostrar;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JTable tblP;
    private javax.swing.JTextField txtClave;
    // End of variables declaration//GEN-END:variables
}
