
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kevin Majarrez
 */
public class Principal extends javax.swing.JFrame {
    DefaultTableModel m = new DefaultTableModel();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        m.addColumn("ID_PRODUCTOS");
        m.addColumn("DESCRIPCION");
        m.addColumn("PRECIO");
        m.addColumn("EXISTENCIA");
        this.setLocationRelativeTo(null);
        tblProductos.setModel(m);
        consulta("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        cmbBuscar = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jcbMostrar = new javax.swing.JCheckBox();
        tbnEliminar = new javax.swing.JButton();
        txtpre = new javax.swing.JTextField();
        lbldes = new javax.swing.JLabel();
        lblpre = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();
        txtexi = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Domicilio", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        lblClave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblClave.setText("Clave");

        lblBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBuscar.setText("Buscar en");

        cmbBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NOMBRE", "DIRECCION", "TELEFONO" }));

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jcbMostrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbMostrar.setSelected(true);
        jcbMostrar.setText("Mostrar todos");
        jcbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMostrarActionPerformed(evt);
            }
        });

        tbnEliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbnEliminar.setText("Eliminar");
        tbnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnEliminarActionPerformed(evt);
            }
        });

        lbldes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbldes.setText("Descripción");

        lblpre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblpre.setText("Precio");

        lbltel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbltel.setText("Existencia");

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Insertar");

        btnIngresar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tabla Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBuscar, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbMostrar))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbldes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtdes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtpre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtexi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnIngresar)
                        .addGap(7, 7, 7)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldes)
                                .addGap(4, 4, 4)
                                .addComponent(lblpre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblClave)
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBuscar)
                                    .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jcbMostrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtexi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String where = "";
        
        jcbMostrar.setSelected(false);
        switch(cmbBuscar.getSelectedIndex()){
            case 0:
                where = "WHERE ID = "+txtClave.getText();
                break;
            default:
                where = "WHERE "+cmbBuscar.getSelectedItem().toString().toUpperCase()+
                        " LIKE '%"+txtClave.getText()+"%'";
        }
        consulta(where);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jcbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMostrarActionPerformed
        jcbMostrar.setSelected(true);
        consulta("");
        
    }//GEN-LAST:event_jcbMostrarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String id="";
        try{
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/practica1","root","");
            Statement s = conexion.createStatement();
            String SQL = "INSERT INTO `practica1`.`Productos` (`ID_PRODUCTOS`, `DESCRIPCION`, `PRECIO`, `EXISTENCIA`) VALUES (NULL, '%des', '%pre', '%exi');";
            SQL = SQL.replace("%des",txtdes.getText());
            SQL = SQL.replace("%pre",txtpre.getText());
            SQL = SQL.replace("%exi",txtexi.getText());
            int respuesta = s.executeUpdate(SQL);
            String texto ="";
            if(respuesta!=0){
                texto = "SE INSERTO CORRECTAMENTE";
            }else{
                texto="Error no se pudo insertar";
            }
            mensaje(texto);
            txtpre.setText("");
            txtexi.setText("");
            txtdes.setText("");
            conexion.close();
        }catch(Exception e){
            mensaje(e.getMessage());
        }
         consulta("");
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(tblProductos.getSelectedRow()<0){
            mensaje("ERORR\n DEBES SELECCIONAR EL RENGLON DE LA TABLA PARA PODER ACTUALIZAR");
        return;
        }
        String id = m.getValueAt(tblProductos.getSelectedRow(), 0).toString();
        
        try{
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/practica1","root","");
            Statement s = conexion.createStatement();
            
            String SQL = "UPDATE `Productos` SET  `DESCRIPCION`='%des', `PRECIO`='%pre', `EXISTENCIA`='%exi' WHERE `ID_PRODUCTOS` = "+id;
            SQL = SQL.replace("%des",txtdes.getText());
            SQL = SQL.replace("%pre",txtpre.getText());
            SQL = SQL.replace("%exi",txtexi.getText());
            int respuesta = s.executeUpdate(SQL);
            String texto ="ERROR NO SE PUDO ACTUALIZAR";
            if(respuesta!=0){
                texto = "SE ACTUALIZO CORRECTAMENTE";
            }else{
                mensaje(texto);
            }
            mensaje(texto);
            txtpre.setText("");
            txtexi.setText("");
            txtdes.setText("");
            conexion.close();
        }catch(Exception e){
            mensaje(e.getMessage());
        }
         consulta("");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tbnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnEliminarActionPerformed
        if(tblProductos.getSelectedRow()<0){
            mensaje("ERORR\n DEBES SELECCIONAR EL RENGLON DE LA TABLA PARA PODER ELIMINAR");
        return;
        }
        String id = m.getValueAt(tblProductos.getSelectedRow(), 0).toString();
        int resp = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas eliminar ID_PRODUCTOS"+id);
        if(resp == JOptionPane.OK_OPTION){
            eliminar(id);
        }
        consulta("");
    }//GEN-LAST:event_tbnEliminarActionPerformed

    
    public void consulta(String where){
        try{
           DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/practica1","root","");
           Statement s = conexion.createStatement();
           String SQL = "SELECT * FROM `practica1`.`Productos`";
           
           if(where.isEmpty()){
               //Entra si el where NO esta vacio
        SQL += where;
    }           
           ResultSet resultadoConsulta = s.executeQuery(SQL);
           
           //Este if es para ¿Existen renglones de consulta anterior?
           if(m.getRowCount()>0){
               //Si hay renglones, el sig. ciclo los BORRA
               int total = m.getRowCount();
               for (int i = 1; i <= total; i++) {
                   m.removeRow(0);
               }
           }
           
           while(resultadoConsulta.next()){
               String[] data = new String[4];
               data[0] = ""+resultadoConsulta.getInt(1);
               data[1] = ""+resultadoConsulta.getString(2);
               data[2] = ""+resultadoConsulta.getFloat(3);
               data[3] = ""+resultadoConsulta.getInt(4);
               m.addRow(data);
           }
           conexion.close();
        }catch(Exception e){mensaje(e.getMessage());}
    }
    private void eliminar(String id){
        try{
           DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/practica1","root","");
           Statement s = conexion.createStatement();
           String SQL = "DELETE FROM `Productos` WHERE ID_PRODUCTOS = "+id;
           
           int resultado = s.executeUpdate(SQL);
           
           if(resultado == 0){
               mensaje("ERROR:\nNo se pudo eliminar ID_PRODUCTOS"+id);
           }else{
               mensaje("¡SE BORRO CON EXITO!");
           }
             conexion.close();
    }   catch (SQLException e) {
            mensaje(e.getMessage());
    }    
        consulta("");
    }//eliminar//eliminar
    
    private void mensaje(String m){
        JOptionPane.showMessageDialog(this,m);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbMostrar;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lbldes;
    private javax.swing.JLabel lblpre;
    private javax.swing.JLabel lbltel;
    private javax.swing.JTable tblProductos;
    private javax.swing.JButton tbnEliminar;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtexi;
    private javax.swing.JTextField txtpre;
    // End of variables declaration//GEN-END:variables
}
